### ISSUE TITLE
probably wrong source url in META.info

### ISSUE THREAD

**Issue by FROGGS** [dnmfarrell/System-Passwd#3]
Should'nt this https://github.com/dnmfarrell/System-Passwd/blob/master/META.info#L7 point to `git://github.com/dnmfarrell/System-Passwd.git` ?

**Comment by dnmfarrell** [comment]
Thanks for this, I fixed the reference. I changed my GitHub username recently, hence the discrepancy. The previous URL still works though (it redirects).
